chore: zsec and docs enhancements

diff --git a/examples/zsec b/examples/zsec
--- a/examples/zsec
+++ b/examples/zsec
@@ -128,17 +128,52 @@ echo "Checking GCP Environment Variables and Cloud Connector bootstrap requireme
 # if .zsecrc is not present we'll assume that GCO env was never set
 gcp_location_default="us-central1"
 project_id_default="cc-poc-host-project-01"
-ccvm_instance_img_default="developer-image-gcp-freebsd11-202307262326"
+ccvm_instance_img_default="developer-image-gcp-freebsd11-202308100252"
 
 if [[ ! -e ./.zsecrc ]]; then
-    read -r -p "Enter Google Cloud Host Project Credential File Path: " gcp_credentials
-    if [ -z "$gcp_credentials" ];then
-      echo "Invalid Google Cloud Host Project credentials entered."
-      echo "Delete .zsecrc file and re-run zsec up..."
-      exit 1
-    fi
-    echo "export TF_VAR_credentials=${gcp_credentials}" >> .zsecrc
+    for file in ./$dtype/credentials/*.json; 
+do 
+json_lookup=$(basename ./$dtype/credentials/*.json)
+if [[ $json_lookup == "*.json" ]]; then
+echo "The Service Account JSON file could not be found in the directory ${dtype}/credentials..."
+read -r -p "Enter Google Cloud Host Project Credential JSON full file path: " manual_gcp_credentials
+    manual_file_check=$manual_gcp_credentials
+if test -f "$manual_file_check"; then
+    echo "JSON file: $manual_gcp_credentials will be used..."
+    gcp_credentials=$manual_gcp_credentials
+else
+    echo "JSON path invalid. Please confirm filename and path are correct and re-run zsec..."
+    exit 1    
+fi
 
+else
+while true; do
+read -r -p "Service Account JSON file named ${json_lookup} identified in directory ${dtype}/credentials. Is this the correct JSON to use? (yes/no): " json_lookup_response
+case $json_lookup_response in 
+	yes|y )
+    gcp_credentials=./credentials/$json_lookup
+    echo "Using $gcp_credentials for deployment..."
+    break
+    ;;
+    no|n )
+    read -r -p "Copy JSON file to $dtype/credentials/ and enter filename here (e.g. serviceaccountname.json): " json_manual_input
+    file_check=./$dtype/credentials/$json_manual_input
+if test -f "$file_check"; then
+    echo "JSON name $json_manual_input will be used..."
+    gcp_credentials=./credentials/$json_manual_input
+else
+    echo "JSON does not exist by this name. Please confirm filename and path are correct and re-run zsec..."
+    exit 1    
+fi
+    break
+    ;;
+	* ) echo "invalid response. Please enter yes or no";;
+    esac
+done
+fi
+break
+done
+    echo "export TF_VAR_credentials=${gcp_credentials}" >> .zsecrc
     read -r -p "Enter Google Cloud Host Project ID[Default=$project_id_default]: " project_id
     project_id=${project_id:-$project_id_default}
     echo "export TF_VAR_project=${project_id}" >> .zsecrc
